- hosts: masters
  remote_user: devadmin
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: generate kubeadm init
      shell: |
        wget https://docs.projectcalico.org/manifests/calico.yaml
        sudo kubeadm config print init-defaults | tee ClusterConfiguration.yaml
        sudo sed -i 's/  advertiseAddress: 1.2.3.4/  advertiseAddress: 192.168.97.74/' ClusterConfiguration.yaml
        sudo sed -i 's/  criSocket: \/var\/run\/dockershim\.sock/  criSocket: \/run\/containerd\/containerd\.sock/' ClusterConfiguration.yaml
        sudo sed -i 's/  name: node/  name: amsl-qa-master/' ClusterConfiguration.yaml

    - name: install clusterconfiguration file updated
      shell: |
        cat <<EOF | cat >>  ClusterConfiguration.yaml
        ---
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        cgroupDriver: systemd
        EOF

    - name: initialize the cluster
      become: yes
      become_user: devadmin
      shell: sudo kubeadm init --config=ClusterConfiguration.yaml --cri-socket /run/containerd/containerd.sock
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's home directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/.kube/config
        remote_src: yes
        owner: devadmin

    - name: install Pod network
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      shell: |
        openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //' 
        kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
