- hosts: "workers, masters"
  become: yes

  tasks:
    - name: Login as Root user
      command: sudo -i

    - name: create the maidul user account
      user: name=maidul append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'maidul' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: "maidul ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: set up authorized keys for the maidul user
      authorized_key: user=maidul key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
